//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class express
    {
        public string id { get; set; }
        public string name { get; set; }
        public string telephoone { get; set; }
        public string state { get; set; }
        public Nullable<System.DateTime> intime { get; set; }
        public string scid { get; set; }
        public Nullable<System.DateTime> outtime { get; set; }
        public string qrcode { get; set; }
        public string logisticid { get; set; }
    }
}
