//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class socketlog
    {
        public string id { get; set; }
        public System.DateTime datetime { get; set; }
        public string cmdtype { get; set; }
        public string senddata { get; set; }
        public Nullable<bool> isreq { get; set; }
        public string note { get; set; }
        public string clientip { get; set; }
    }
}
